In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler

In [4]:
df=pd.read_csv(r"C:\Users\aksha\Downloads\Universities.csv",index_col="Univ")

In [5]:
df

SAT  Top10  Accept  SFRatio  Expenses  GradRate
Univ                                                          
Brown         1310     89      22       13     22704        94
CalTech       1415    100      25        6     63575        81
CMU           1260     62      59        9     25026        72
Columbia      1310     76      24       12     31510        88
Cornell       1280     83      33       13     21864        90
Dartmouth     1340     89      23       10     32162        95
Duke          1315     90      30       12     31585        95
Georgetown    1255     74      24       12     20126        92
Harvard       1400     91      14       11     39525        97
JohnsHopkins  1305     75      44        7     58691        87
MIT           1380     94      30       10     34870        91
Northwestern  1260     85      39       11     28052        89
NotreDame     1255     81      42       13     15122        94
PennState     1081     38      54       18     10185        80
Princeton     1375     91      14        8     30220        95
Purdue        1005     28      90       19      9066        69
Stanford      1360     90      20       12     36450        93
TexasA&M      1075     49      67       25      8704        67
UCBerkeley    1240     95      40       17     15140        78
UChicago      1290     75      50       13     38380        87
UMichigan     1180     65      68       16     15470        85
UPenn         1285     80      36       11     27553        90
UVA           1225     77      44       14     13349        92
UWisconsin    1085     40      69       15     11857        71
Yale          1375     95      19       11     43514        96

In [6]:
std=StandardScaler()

In [7]:
df1=pd.DataFrame(std.fit_transform(df),columns=df.columns)

In [8]:
df1

SAT     Top10    Accept   SFRatio  Expenses  GradRate
0   0.410284  0.657519 -0.889867  0.070260 -0.331413  0.820303
1   1.399259  1.235212 -0.734657 -1.686251  2.560381 -0.644524
2  -0.060657 -0.760454  1.024382 -0.933460 -0.167121 -1.658634
3   0.410284 -0.025208 -0.786394 -0.180670  0.291649  0.144229
4   0.127719  0.342414 -0.320766  0.070260 -0.390846  0.369587
5   0.692848  0.657519 -0.838130 -0.682530  0.337780  0.932982
6   0.457378  0.710037 -0.475975 -0.180670  0.296955  0.932982
7  -0.107751 -0.130243 -0.786394 -0.180670 -0.513817  0.594945
8   1.257977  0.762555 -1.303758 -0.431600  0.858743  1.158339
9   0.363190 -0.077726  0.248335 -1.435321  2.214818  0.031550
10  1.069601  0.920107 -0.475975 -0.682530  0.529383  0.482266
11 -0.060657  0.447449 -0.010347 -0.431600  0.046981  0.256908
12 -0.107751  0.237379  0.144862  0.070260 -0.867871  0.820303
13 -1.746625 -2.020875  0.765699  1.324911 -1.217184 -0.757202
14  1.022507  0.762555 -1.303758 -1.184390  0.200376  0.932982
15 -2.462455 -2.546050  2.628211  1.575841 -1.296358 -1.996671
16  0.881224  0.710037 -0.993340 -0.180670  0.641174  0.707624
17 -1.803138 -1.443182  1.438273  3.081422 -1.321971 -2.222029
18 -0.249033  0.972625  0.041389  1.073981 -0.866597 -0.982560
19  0.221907 -0.077726  0.558754  0.070260  0.777730  0.031550
20 -0.814162 -0.602901  1.490010  0.823051 -0.843248 -0.193808
21  0.174813  0.184862 -0.165557 -0.431600  0.011674  0.369587
22 -0.390316  0.027309  0.248335  0.321191 -0.993318  0.594945
23 -1.708950 -1.915840  1.541746  0.572121 -1.098883 -1.771313
24  1.022507  0.972625 -1.045076 -0.431600  1.140982  1.045661

In [10]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   SAT       25 non-null     float64
 1   Top10     25 non-null     float64
 2   Accept    25 non-null     float64
 3   SFRatio   25 non-null     float64
 4   Expenses  25 non-null     float64
 5   GradRate  25 non-null     float64
dtypes: float64(6)
memory usage: 1.3 KB


### create the model

In [11]:
from sklearn.decomposition import PCA

In [12]:
model=PCA(n_components=6)#here we mention 6 then we will get 6 pca(6 lines)

In [14]:
model.fit_transform(df1)

array([[-1.00987445e+00, -1.06430962e+00,  8.10663051e-02,
         5.69506350e-02, -1.28754245e-01, -3.46496377e-02],
       [-2.82223781e+00,  2.25904458e+00,  8.36828830e-01,
         1.43844644e-01, -1.25961913e-01, -1.80703168e-01],
       [ 1.11246577e+00,  1.63120889e+00, -2.66786839e-01,
         1.07507502e+00, -1.91814148e-01,  3.45679459e-01],
       [-7.41741217e-01, -4.21874699e-02,  6.05008649e-02,
        -1.57208116e-01, -5.77611392e-01,  1.09163092e-01],
       [-3.11912064e-01, -6.35243572e-01,  1.02405189e-02,
         1.71363672e-01,  1.27261287e-02, -1.69212696e-02],
       [-1.69669089e+00, -3.44363283e-01, -2.53407507e-01,
         1.25643278e-02, -5.26606002e-02, -2.71661600e-02],
       [-1.24682093e+00, -4.90983662e-01, -3.20938196e-02,
        -2.05643780e-01,  2.93505340e-01, -7.80119838e-02],
       [-3.38749784e-01, -7.85168589e-01, -4.93584829e-01,
         3.98563085e-02, -5.44978619e-01, -1.55371653e-01],
       [-2.37415013e+00, -3.86538883e-01,  1.160

In [16]:
var=model.explained_variance_ratio_
var#here the 6 numbers are 6 pca and its varience

array([0.76868084, 0.13113602, 0.04776031, 0.02729668, 0.0207177 ,
       0.00440844])

In [17]:
np.cumsum(var)

array([0.76868084, 0.89981687, 0.94757718, 0.97487386, 0.99559156,
       1.        ])

In [18]:
#here we select frist 3 pca with total varienc=94.7 %

In [19]:
final_model=PCA(n_components=3)
final_model.fit_transform(df1)

array([[-1.00987445, -1.06430962,  0.08106631],
       [-2.82223781,  2.25904458,  0.83682883],
       [ 1.11246577,  1.63120889, -0.26678684],
       [-0.74174122, -0.04218747,  0.06050086],
       [-0.31191206, -0.63524357,  0.01024052],
       [-1.69669089, -0.34436328, -0.25340751],
       [-1.24682093, -0.49098366, -0.03209382],
       [-0.33874978, -0.78516859, -0.49358483],
       [-2.37415013, -0.38653888,  0.11609839],
       [-1.40327739,  2.11951503, -0.44282714],
       [-1.72610332,  0.08823712,  0.17040366],
       [-0.45085748, -0.01113295, -0.17574605],
       [ 0.04023814, -1.00920438, -0.49651717],
       [ 3.23373034, -0.37458049, -0.49537282],
       [-2.23626502, -0.37179329, -0.39899365],
       [ 5.17299212,  0.77991535, -0.38591233],
       [-1.69964377, -0.30559745,  0.31850785],
       [ 4.578146  , -0.34759136,  1.49964176],
       [ 0.82260312, -0.69890615,  1.42781145],
       [-0.09776213,  0.65044645,  0.10050844],
       [ 1.9631826 , -0.22476756, -0.255

### so here we reduce the dimension from 6 to 3

In [22]:
final_model1=PCA(0.90)# this methode is used to give percentage of information we can accept